# Rustfmt configuration
edition = "2021"
max_width = 120
use_small_heuristics = "Default"
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
imports_granularity = "Module"
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"